# Reward players with keys every 300 seconds of being online!
automatic-key-all:
  # Requires a restart to disable/enable.
  enabled: false
  time: 300
  keys:
    common-crate: 1

  alert:
    enabled: true
    sound: ENTITY_EXPERIENCE_ORB_PICKUP

    # These will be ignored if you leave them empty.
    title: '&aKey All'
    subtitle: '&a1 Common key'

database:
  thread-pool-size: 2

